# Generated by Django 5.0.4 on 2024-04-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "발행"),
                    ("HIDDEN", "숨김"),
                    ("DELETED", "삭제"),
                ],
                default="PUBLISHED",
                max_length=20,
            ),
        ),
    ]
