[tool.poetry]
name = "post-command"
version = "0.1.0"
description = "post command practice"
authors = ["y"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0.4"
black = "^24.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
